name: simple_logger
description: Simple logger that provides some colorful log capabilities.
version: 1.0.0
# repository: https://github.com/ruchan-o7/dart_simple_logger/tree/main

environment:
  sdk: ^3.1.4

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
